<a href="https://colab.research.google.com/github/TerteryanTatev/Optimization-Methods/blob/main/Linear_Regression_Practical_Analysis/linear_regression_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import pandas as pd
df = pd.DataFrame({
    'n': [i for i in range(1, 21)],
    'x1': [1, 2, 2, 1, 1, 1, 3, 1, 1, 1, 1, 4, 3, 1, 1, 1, 3, 2, 1, 2],
    'x2': [1, 1, 1, 1, 1, 1, 2, 2, 1, 3, 2, 3, 1, 1, 2, 1, 3, 2, 2, 3],
    'x3': [2, 3, 2, 1, 3, 2, 3, 3, 1, 4, 3, 4, 3, 2, 4, 1, 4, 3, 3, 4],
    'y' : [15000, 28000, 26000, 17000, 18000, 14000, 42000, 19000, 13500,
           21000, 22000, 48000, 30000, 18500, 23000, 16000, 37000, 24000,
           17500, 28000]
})

print(df)


     n  x1  x2  x3      y
0    1   1   1   2  15000
1    2   2   1   3  28000
2    3   2   1   2  26000
3    4   1   1   1  17000
4    5   1   1   3  18000
5    6   1   1   2  14000
6    7   3   2   3  42000
7    8   1   2   3  19000
8    9   1   1   1  13500
9   10   1   3   4  21000
10  11   1   2   3  22000
11  12   4   3   4  48000
12  13   3   1   3  30000
13  14   1   1   2  18500
14  15   1   2   4  23000
15  16   1   1   1  16000
16  17   3   3   4  37000
17  18   2   2   3  24000
18  19   1   2   3  17500
19  20   2   3   4  28000


In [ ]:
import numpy as np
x1_mean, x2_mean, x3_mean, y_mean = df['x1'].mean(), df['x2'].mean(), df['x3'].mean(), df['y'].mean()

df['x1_'] = df['x1'] - x1_mean
df['x2_'] = df['x2'] - x2_mean
df['x3_'] = df['x3'] - x3_mean
df['y_']  = df['y']  - y_mean
print(df[['x1_', 'x2_', 'x3_', 'y_']])



sx1 = np.sqrt(np.sum(df['x1_']**2)/(len(df)-1))
sx2 = np.sqrt(np.sum(df['x2_']**2)/(len(df)-1))
sx3 = np.sqrt(np.sum(df['x3_']**2)/(len(df)-1))
sy  = np.sqrt(np.sum(df['y_']**2)/(len(df)-1))
print("Ստանդարտ շեղումներ:"f"sx1 = {sx1:.4f}, sx2 = {sx2:.4f}, sx3 = {sx3:.4f}, sy = {sy:.4f}\n")

def r(a,b):
    return np.sum((a - a.mean())*(b - b.mean())) / np.sqrt(np.sum((a - a.mean())**2)*np.sum((b - b.mean())**2))

r_yx1 = r(df['y'], df['x1'])
r_yx2 = r(df['y'], df['x2'])
r_yx3 = r(df['y'], df['x3'])

r_x1x2 = r(df['x1'], df['x2'])
r_x1x3 = r(df['x1'], df['x3'])
r_x2x3 = r(df['x2'], df['x3'])

print("Կորելյացիաներ՝")
print(f"r(y,x1) = {r_yx1:.4f}")
print(f"r(y,x2) = {r_yx2:.4f}")
print(f"r(y,x3) = {r_yx3:.4f}")
print(f"r(x1,x2) = {r_x1x2:.4f}")
print(f"r(x1,x3) = {r_x1x3:.4f}")
print(f"r(x2,x3) = {r_x2x3:.4f}")
print()


R = np.array([
    [1,        r_x1x2, r_x1x3],
    [r_x1x2,   1,      r_x2x3],
    [r_x1x3,   r_x2x3, 1]
])
print("R=",R)
R0 = np.array([r_yx1, r_yx2, r_yx3])
print("R0",R0)

a = np.linalg.inv(R) @ R0

a1, a2, a3 = a
print("Ստանդարտացված (β) գործակիցներ՝")
print(f"a1 = {a1:.4f}, a2 = {a2:.4f}, a3 = {a3:.4f}")
print()

b1 = a1 * (sy / sx1)
b2 = a2 * (sy / sx2)
b3 = a3 * (sy / sx3)

b0 = y_mean - (b1*x1_mean + b2*x2_mean + b3*x3_mean)

print("Ռեգրեսիոն հավասարման գործակիցներ՝")
print(f"b0 = {b0:.4f}")
print(f"b1 = {b1:.4f}")
print(f"b2 = {b2:.4f}")
print(f"b3 = {b3:.4f}")
print()
print(f"Վերջնական հավասարում՝ ŷ = {b0:.4f} + {b1:.4f}x1 + {b2:.4f}x2 + {b3:.4f}x3")


     x1_  x2_   x3_       y_
0  -0.65 -0.7 -0.75  -8875.0
1   0.35 -0.7  0.25   4125.0
2   0.35 -0.7 -0.75   2125.0
3  -0.65 -0.7 -1.75  -6875.0
4  -0.65 -0.7  0.25  -5875.0
5  -0.65 -0.7 -0.75  -9875.0
6   1.35  0.3  0.25  18125.0
7  -0.65  0.3  0.25  -4875.0
8  -0.65 -0.7 -1.75 -10375.0
9  -0.65  1.3  1.25  -2875.0
10 -0.65  0.3  0.25  -1875.0
11  2.35  1.3  1.25  24125.0
12  1.35 -0.7  0.25   6125.0
13 -0.65 -0.7 -0.75  -5375.0
14 -0.65  0.3  1.25   -875.0
15 -0.65 -0.7 -1.75  -7875.0
16  1.35  1.3  1.25  13125.0
17  0.35  0.3  0.25    125.0
18 -0.65  0.3  0.25  -6375.0
19  0.35  1.3  1.25   4125.0
Ստանդարտ շեղումներ:sx1 = 0.9333, sx2 = 0.8013, sx3 = 1.0195, sy = 9437.9901

Կորելյացիաներ՝
r(y,x1) = 0.9418
r(y,x2) = 0.5654
r(y,x3) = 0.6010
r(x1,x2) = 0.4152
r(x1,x3) = 0.4563
r(x2,x3) = 0.8053

R= [[1.         0.41521506 0.45632199]
 [0.41521506 1.         0.80527932]
 [0.45632199 0.80527932 1.        ]]
R0 [0.94182406 0.56544079 0.60097861]
Ստանդարտացված (β) գործակիցներ՝
a1 = 0.8360,

In [ ]:
A = np.array([
    [20, df['x1'].sum(), df['x2'].sum(), df['x3'].sum()],
    [df['x1'].sum(), df['x1'] @ df['x1'], df['x1'] @ df['x2'], df['x1'] @ df['x3']],
    [df['x2'].sum(), df['x2'] @ df['x1'], df['x2'] @ df['x2'], df['x2'] @ df['x3']],
    [df['x3'].sum(), df['x3'] @ df['x1'], df['x3'] @ df['x2'], df['x3'] @ df['x3']],
])
print(A)

[[ 20  33  34  55]
 [ 33  71  62  99]
 [ 34  62  70 106]
 [ 55  99 106 171]]


In [ ]:
C=np.array([df['y'].sum(),
            df['x1'] @ df['y'],
            df['x2'] @ df['y'],
            df['x3'] @ df['y'],
])
print(C)

[ 477500  945500  893000 1423000]


In [ ]:
A_inv = np.linalg.inv(A)
b = A_inv @ C
print("b=",b)
print("A_inv=",A_inv)

b= [4394.53125    8454.26053779 1392.71438953 1150.29978198]
A_inv= [[ 0.453125   -0.0390625   0.015625   -0.1328125 ]
 [-0.0390625   0.07694404 -0.01217297 -0.02443677]
 [ 0.015625   -0.01217297  0.23510174 -0.14371366]
 [-0.1328125  -0.02443677 -0.14371366  0.15179869]]


In [ ]:
df['y_hat'] = b[0] + b[1]*df['x1'] + b[2]*df['x2'] + b[3]*df['x3']
df

,n,x1,x2,x3,y,y_hat
0,1,1,1,2,1,1.205305
1,2,2,1,3,3,2.406613
2,3,2,1,2,3,2.180233
3,4,1,1,1,1,0.978924
4,5,1,1,3,1,1.431686
5,6,1,1,2,1,1.205305
6,7,3,2,3,4,3.440407
7,8,1,2,3,1,1.490552
8,9,1,1,1,1,0.978924
9,10,1,3,4,2,1.775799
