<a href="https://colab.research.google.com/github/TerteryanTatev/Optimization-Methods/blob/main/Linear_Regression_Model_Estimation/regression_model_estimation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.DataFrame({
    'N': [ i for i in range(1,21)],
    'X1': [1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2],
    'X2': [4, 3, 1, 2, 2, 1, 4, 3, 2, 1, 2, 3, 4, 4, 1, 2, 1, 3, 3, 1],
    'X3': [2, 1, 5, 1, 4, 3, 2, 5, 3, 1, 4, 3, 5, 1, 3, 4, 5, 1, 5, 4],
    'Y':  [50, 22, 65, 38, 58, 34, 54, 95, 40, 18, 60, 52, 100, 45, 36, 61, 59, 32, 89, 88]
})

df

,N,X1,X2,X3,Y
0,1,1,4,2,50
1,2,1,3,1,22
2,3,2,1,5,65
3,4,1,2,1,38
4,5,1,2,4,58
5,6,2,1,3,34
6,7,2,4,2,54
7,8,2,3,5,95
8,9,1,2,3,40
9,10,1,1,1,18


In [ ]:
x1_mean, x2_mean, x3_mean, y_mean = df['X1'].mean(), df['X2'].mean(), df['X3'].mean(), df['Y'].mean()

df['x1_'] = df['X1'] - x1_mean
df['x2_'] = df['X2'] - x2_mean
df['x3_'] = df['X3'] - x3_mean
df['y_']  = df['Y']  - y_mean


sx1 = np.sqrt(np.sum(df['x1_']**2)/19)
sx2 = np.sqrt(np.sum(df['x2_']**2)/19)
sx3 = np.sqrt(np.sum(df['x3_']**2)/19)
sy  = np.sqrt(np.sum(df['y_']**2)/19)
print("Ստանդարտ շեղումներ:"f"sx1 = {sx1:.4f}, sx2 = {sx2:.4f}, sx3 = {sx3:.4f}, sy = {sy:.4f}\n")

Ստանդարտ շեղումներ:sx1 = 0.5130, sx2 = 1.1367, sx3 = 1.5526, sy = 23.5005



In [ ]:

def r(a,b):
    return np.sum((a - a.mean())*(b - b.mean())) / np.sqrt(np.sum((a - a.mean())**2)*np.sum((b - b.mean())**2))

r_yx1 = r(df['Y'], df['X1'])
r_yx2 = r(df['Y'], df['X2'])
r_yx3 = r(df['Y'], df['X3'])

r_x1x2 = r(df['X1'], df['X2'])
r_x1x3 = r(df['X1'], df['X3'])
r_x2x3 = r(df['X2'], df['X3'])

print("Կորելյացիաներ՝")
print(f"r(y,x1) = {r_yx1:.4f}")
print(f"r(y,x2) = {r_yx2:.4f}")
print(f"r(y,x3) = {r_yx3:.4f}")
print(f"r(x1,x2) = {r_x1x2:.4f}")
print(f"r(x1,x3) = {r_x1x3:.4f}")
print(f"r(x2,x3) = {r_x2x3:.4f}")


,N,X1,X2,X3,Y,X1_,X2_,X3_,Y_,x1_,x2_,x3_,y_,Y_hat
0,1,1,4,2,50,-0.5,1.65,-1.1,-4.8,-0.5,1.65,-1.1,-4.8,50.824179
1,2,1,3,1,22,-0.5,0.65,-2.1,-32.8,-0.5,0.65,-2.1,-32.8,29.158679
2,3,2,1,5,65,0.5,-1.35,1.9,10.2,0.5,-1.35,1.9,10.2,71.949927
3,4,1,2,1,38,-0.5,-0.35,-2.1,-16.8,-0.5,-0.35,-2.1,-16.8,20.842091
4,5,1,2,4,58,-0.5,-0.35,0.9,3.2,-0.5,-0.35,0.9,3.2,60.888827
5,6,2,1,3,34,0.5,-1.35,-0.1,-20.8,0.5,-1.35,-0.1,-20.8,45.252103
6,7,2,4,2,54,0.5,1.65,-1.1,-0.8,0.5,1.65,-1.1,-0.8,56.852955
7,8,2,3,5,95,0.5,0.65,1.9,40.2,0.5,0.65,1.9,40.2,88.583103
8,9,1,2,3,40,-0.5,-0.35,-0.1,-14.8,-0.5,-0.35,-0.1,-14.8,47.539915
9,10,1,1,1,18,-0.5,-1.35,-2.1,-36.8,-0.5,-1.35,-2.1,-36.8,12.525503


In [ ]:
R = np.array([
    [1,       r_x1x2,  r_x1x3],
    [r_x1x2,  1,       r_x2x3],
    [r_x1x3,  r_x2x3,  1]
])
R

array([[ 1.        ,  0.04512937,  0.13216372],
       [ 0.04512937,  1.        , -0.22963191],
       [ 0.13216372, -0.22963191,  1.        ]])

In [ ]:
R0 = np.array([
    [r_yx1],
    [r_yx2],
    [r_yx3]
])
R0

array([[0.26631207],
       [0.2056936 ],
       [0.80692979]])

In [ ]:
a = np.linalg.inv(R) @ R0
a

array([[0.13160131],
       [0.40226936],
       [0.88191075]])

In [ ]:
Z = df[['X1','X2','X3','Y']].apply(lambda x: (x - x.mean())/x.std())
Z

,X1,X2,X3,Y
0,-0.974679,1.451560,-0.708495,-0.204251
1,-0.974679,0.571827,-1.352581,-1.395715
2,0.974679,-1.187640,1.223764,0.434033
3,-0.974679,-0.307907,-1.352581,-0.714878
4,-0.974679,-0.307907,0.579678,0.136167
5,0.974679,-1.187640,-0.064409,-0.885087
6,0.974679,1.451560,-0.708495,-0.034042
7,0.974679,0.571827,1.223764,1.710602
8,-0.974679,-0.307907,-0.064409,-0.629774
9,-0.974679,-1.187640,-1.352581,-1.565924


In [ ]:
Z_Y = Z['X1']*a[0] + Z['X2']*a[1] + Z['X3']*a[2]
Z_Y

,0
0,-0.169180
1,-1.091097
2,0.729768
3,-1.444986
4,0.259093
5,-0.406285
6,0.087358
7,1.437548
8,-0.308933
9,-1.798876


In [ ]:
Y_hat = df['Y'].mean() + Z_Y * df['Y'].std()
Y_hat

,0
0,50.824179
1,29.158679
2,71.949927
3,20.842091
4,60.888827
5,45.252103
6,56.852955
7,88.583103
8,47.539915
9,12.525503


In [ ]:
df['Y_hat'] = Y_hat
df

,N,X1,X2,X3,Y,Y_,x1_,x2_,x3_,Y_hat
0,1,1,4,2,50,-4.8,-0.5,1.65,-1.1,50.824179
1,2,1,3,1,22,-32.8,-0.5,0.65,-2.1,29.158679
2,3,2,1,5,65,10.2,0.5,-1.35,1.9,71.949927
3,4,1,2,1,38,-16.8,-0.5,-0.35,-2.1,20.842091
4,5,1,2,4,58,3.2,-0.5,-0.35,0.9,60.888827
5,6,2,1,3,34,-20.8,0.5,-1.35,-0.1,45.252103
6,7,2,4,2,54,-0.8,0.5,1.65,-1.1,56.852955
7,8,2,3,5,95,40.2,0.5,0.65,1.9,88.583103
8,9,1,2,3,40,-14.8,-0.5,-0.35,-0.1,47.539915
9,10,1,1,1,18,-36.8,-0.5,-1.35,-2.1,12.525503


In [ ]:

SSO = np.sum((df["Y"] - y_mean) ** 2)
SSR = np.sum((df["Y_hat"] - y_mean) ** 2)
SSE = np.sum((df["Y"] - df["Y_hat"]) ** 2)
SSO, SSR, SSE


(np.float64(10493.199999999999),
 np.float64(8703.388579834436),
 np.float64(1789.8114201655624))

In [ ]:
R_hat = SSR / SSO
R_hat

np.float64(0.8294313059728622)

In [ ]:
sigma = SSE / (20-4-1)
msr = SSR / 4
f = msr / sigma
f

np.float64(18.23527708375001)

In [ ]:
b1 = a[0] * (sy / sx1)
b2 = a[1] * (sy / sx2)
b3 = a[2] * (sy / sx3)

b0 = y_mean - (b1*x1_mean + b2*x2_mean + b3*x3_mean)
Y_hat2 = b0 + df['X1']*b1 +df['X2']*b2 +df['X3']*b3
df['Y_hat2'] = Y_hat2
df

,N,X1,X2,X3,Y,Y_,x1_,x2_,x3_,Y_hat,Y_hat2
0,1,1,4,2,50,-4.8,-0.5,1.65,-1.1,50.824179,50.824179
1,2,1,3,1,22,-32.8,-0.5,0.65,-2.1,29.158679,29.158679
2,3,2,1,5,65,10.2,0.5,-1.35,1.9,71.949927,71.949927
3,4,1,2,1,38,-16.8,-0.5,-0.35,-2.1,20.842091,20.842091
4,5,1,2,4,58,3.2,-0.5,-0.35,0.9,60.888827,60.888827
5,6,2,1,3,34,-20.8,0.5,-1.35,-0.1,45.252103,45.252103
6,7,2,4,2,54,-0.8,0.5,1.65,-1.1,56.852955,56.852955
7,8,2,3,5,95,40.2,0.5,0.65,1.9,88.583103,88.583103
8,9,1,2,3,40,-14.8,-0.5,-0.35,-0.1,47.539915,47.539915
9,10,1,1,1,18,-36.8,-0.5,-1.35,-2.1,12.525503,12.525503


In [ ]:
b0, b1, b2, b3

(array([-15.16877386]),
 array([6.02877636]),
 array([8.31658799]),
 array([13.34891211]))