<a href="https://colab.research.google.com/github/TerteryanTatev/Systems-Modeling-and-Simulation/blob/main/Faddeev-LeVerrier-Algorithm/faddeev_leverrier_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sympy as sp
A = np.array([
[2, -1, 0],
[-1, 2, -1],
[0, -1, 2]
])
n = A.shape[0]

def l(A):
  n = A.shape[0]
  a = A
  per = []
  ser = []
  for i in range(1,n+1):
    s = sum(a[i][i] for i in range(n))
    ser.append(s)
    a = a @ A
    k = -1
    b = ser[k]
    for j in per:
      k-=1
      b -= ser[k] * j
    p = (1/i) * b
    per.append(p)




  return per


p = l(A)

print(p)

[np.float64(6.0), np.float64(-10.0), np.float64(4.0)]


In [ ]:
import numpy as np


def f(A):
    n = A.shape[0]
    I = np.eye(n)
    B = I.copy()
    per = []
    B_prev = None
    for k in range(1, n+1):
        Ak = A @ B
        pk = np.trace(Ak) / k
        per.append(pk)

        B_prev = B.copy()
        B = Ak - pk * I


    inv = B_prev / per[-1]
    return  per, inv




p, inv = f(A)


print(p)

print(f"{(-1)**n}λ^3 + ({p[0]}) λ^2 + ({p[1]}) λ + ({p[2]})")


print(inv)
print(inv @ A)


[np.float64(6.0), np.float64(-10.0), np.float64(4.0)]
-1λ^3 + (6.0) λ^2 + (-10.0) λ + (4.0)
[[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
