<a href="https://colab.research.google.com/github/TerteryanTatev/Optimization-Methods/blob/main/Linear_Regression_Practical_Analysis/residual_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'N': [ i for i in range(1,16)],
    'x' :[4.7, 2.3, 3.0, 1.5, 3.1, 2.6, 1.0, 1.7, 3.6, 1.6, 4.3, 1.9, 2.0, 5.0, 3.1],
    'z' :[1.8, 2.6, 3.5, 2.1, 3.5, 4.0, 2.0, 4.5, 4.9, 5.2, 2.5, 4.6, 1.4, 0.4, 2.4]
})

df


,N,x,z
0,1,4.7,1.8
1,2,2.3,2.6
2,3,3.0,3.5
3,4,1.5,2.1
4,5,3.1,3.5
5,6,2.6,4.0
6,7,1.0,2.0
7,8,1.7,4.5
8,9,3.6,4.9
9,10,1.6,5.2


In [ ]:

x = df['x'].values
z = df['z'].values
n = len(x)
Sxx = Sxz_anc = Szz_anc = Sxz = Szz = 0
for i in range(1, n):


        Sxx += x[i - 1] **2
        Sxz_anc += x[i - 1] * z[i - 1]
        Szz_anc += z[i - 1] **2
        Sxz += x[i - 1] * z[i]
        Szz += z[i - 1] * z[i]

A1 = np.array([[Sxx, Sxz_anc],
                  [Sxz_anc, Szz_anc]])
B1 = np.array([Sxz, Szz])
print('A1=',A1,'\n','B1=', B1)
a1, b1 = np.linalg.solve(A1, B1)

hn_z1 = np.zeros(n - 1)
SSE = 0.0

for i in range(1, n):
        hn_z1[i - 1] = a1 * x[i - 1] + b1 * z[i - 1]

        SSE += (z[i] - hn_z1[i - 1]) ** 2

sigma1 = np.sqrt(SSE / (n - 3))


print(f'a1= {a1}, b1= {b1}, sigma1 = {sigma1}')
Z1 = pd.DataFrame({
   ' z1': hn_z1
})

Z1




A1= [[177.59 143.25]
 [143.25 159.74]] 
 B1= [167.72 139.47]
a1= 0.8680946601677313, b1= 0.09462526562521881, sigma1 = 0.5374149389995616


,z1
0,4.250370
1,3.284357
2,2.154187
3,3.237044
4,3.803567
5,2.114690
6,4.095677
7,4.679478
8,4.977756
9,2.662288


In [ ]:

Sxx1 = Sxz1 = Szz1 = Sxx2 = Sxz2 = Szz2 = Sx1x2 = Sz1z2 = 0.0
Sx1z = Sz1z = Sx2z = Sz2z = 0.0


for i in range(2, n):
        x1 = x[i - 1]
        z1 = z[i - 1]
        x2 = x[i - 2]
        z2 = z[i - 2]
        x[i - 1] = z[i]


        Sxx1 += x1 * x1
        Sxz1 += x1 * z1
        Szz1 += z1 * z1

        Sxx2 += x2 * x2
        Sxz2 += x2 * z2
        Szz2 += z2 * z2

        Sx1x2 += x1 * x2
        Sz1z2 += z1 * z2

        Sx1z += x1 * x[i - 1]
        Sz1z += z1 * x[i - 1]
        Sx2z += x2 * x[i - 1]
        Sz2z += z2 * x[i - 1]

A2 = np.array([
        [Sxx1, Sxz1, Sx1x2, Sxz2],
        [Sxz1, Szz1, Sz1z2, Szz2],
        [Sx1x2, Sz1z2, Sxx2, Sxz2],
        [Sxz2, Szz2, Sxz2, Szz2]
    ])

B2 = np.array([Sx1z, Sz1z, Sx2z, Sz2z])

print('A2=',A2,'\n','B2=', B2)
a2, b2, c2, d2 = np.linalg.solve(A2, B2)


z2 = np.zeros(n - 2)
SSE = 0.0

for i in range(2, n):
        z2[i - 2] = (
            a2 * x[i - 1] +
            b2 * z[i - 1] +
            c2 * x[i - 2] +
            d2 * z[i - 2]
        )
        res =
        SSE += (z[i] - z2[i - 2]) ** 2

sigma2 = np.sqrt(SSE / (n - 5))



A2= [[155.5  134.79 142.14 142.29]
 [134.79 156.5  138.51 159.58]
 [142.14 138.51 171.83 142.29]
 [142.29 159.58 142.29 159.58]] 
 B2= [155.5  134.79 142.14 135.48]


In [ ]:
print(f'a2= {a2}, b2= {b2}, c2= {a2}, d2= {b2}, sigma2 = {sigma2}')
Z2 = pd.DataFrame({
   ' z2': z2
})

Z2

a2= 0.73049430752269, b2= -1.661417494830406, c2= 0.73049430752269, d2= -1.661417494830406, sigma2 = 3.3521296297496113


,z2
0,1.852270
1,0.655286
2,5.485723
3,1.152440
4,1.398387
5,7.264455
6,0.057204
7,4.100467
8,2.368403
9,8.688126


In [ ]:
s = 0
for i in z:
  s+=i**2
s

np.float64(165.5)